on:
  pull_request:
    types: [ opened ]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: PullRequest Handler
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: PullRequest Handler
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
